pull_request_rules:
    - name: Automatic merge on pull request
      conditions:
          - "#approved-reviews-by>=1"
      actions: 
          merge:
              method: merge
    - name: Automatic merge from develop to master
      conditions:
          - base=master
          - head=develop
      actions:
          merge:
              method: merge